### ISSUE TITLE
Export on Windows Latest fails with `C:\Users\runneradmin\bin\godot' is not recognized as an internal or external command`

### ISSUE THREAD

**Issue by coder137** [chickensoft-games/setup-godot#77]
```yaml
  export-windows-chickensoft:
    name: Windows Export (Chickensoft)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v1.5.6
        name: Setup Godot
        with:
          version: 4.2.1
          use-dotnet: false
      - name: Check Dependencies
        shell: cmd
        run: |
          rustup default
          rustc --version
          echo %GODOT%
          echo %GODOT4%
          where godot
          %GODOT% --version
      - name: Rust and Godot export
        working-directory: ${{github.workspace}}/godot_action_test
        shell: cmd
        run: |
          mkdir ../build/windows
          export_win.bat
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_chickensoft
          path: build/windows
          retention-days: 1
```

On the **Setup Godot** step I see that godot is installed

```
🔧 Adding environment variables...
    GODOT=C:\Users\runneradmin\bin\godot
    GODOT4=C:\Users\runneradmin\bin\godot
```

On the **Check Dependencies** step I get the following log output

```
stable-x86_64-pc-windows-msvc (default)
rustc 1.76.0 (07dca489a 2024-02-04)
C:\Users\runneradmin\bin\godot
C:\Users\runneradmin\bin\godot
C:\Users\runneradmin\bin\godot
'C:\Users\runneradmin\bin\godot' is not recognized as an internal or external command,
operable program or batch file.
```

Raw Logs reference:  [job-logs.txt](https://github.com/chickensoft-games/setup-godot/files/14381617/job-logs.txt)

**Comment by coder137** [comment]
> @coder137 thanks for investigating! can you see if this also fails from a bash shell? I'd like to take a closer look later when I have a chance, but finding that out would help tremendously.

Yes, When using the default shell as bash I could do godot --version now!

```yaml
  export-windows-chickensoft:
    name: Windows Export (Chickensoft)
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
```

So maybe the problem is with using cmd / default windows shell.
Either way, This solves my issue. I can just use bash instead
